### ISSUE TITLE
I got banned 

### ISSUE THREAD

**Issue by anaskhalil421** [AliAryanTech/Texas#1]
Salam...Brother just a few minutes ago i got banned by taxas on WhatsApp for a accidentaly made call.....so please i request you with a great humble is any possibleway to unban....😐🙏

**Comment by AliAryanTech** [comment]
> Salam...Brother just a few minutes ago i got banned by taxas on WhatsApp for a accidentaly made call.....so please i request you with a great humble is any possibleway to unban....😐🙏

😳 Wow.... Personally Email and Message on Telegram Too

**Comment by AliAryanTech** [comment]
> Salam...Brother just a few minutes ago i got banned by taxas on WhatsApp for a accidentaly made call.....so please i request you with a great humble is any possibleway to unban....😐🙏
